name: "Build main-next and dev-next images & releases"

on:
  workflow_dispatch:

jobs:  
# =============================================================================================================================================================================================
  Build-dev-routestrategy-image:
    runs-on: ubuntu-latest
    name: "Build main-next image"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to Docker hub
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          platforms: linux/i386, linux/amd64, linux/arm/v7, linux/arm64
          build-args: BRANCH=dev-routestrategy
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:dev-routestrategy
