name: test

on:
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      BINARY: sing-box

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "arm"
            goos: darwin
          - goarch: "386"
            goos: windows
          - goarch: "arm"
            goos: windows
          - goarch: "arm64"
            goos: windows

    steps:
      - name: Git clone sing-box
        run: |
          VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r '.tag_name')
          GOVERSION=$(curl -s https://go.dev/VERSION?m=text | grep -oP 'go\K\d+(\.\d+)+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV

      - name: Git clone repository
        uses: actions/checkout@v4
        with:
          repository: 'SagerNet/sing-box'
          ref: '${{ env.VERSION }}'
          fetch-depth: 1

      - uses: wangyoucao577/go-release-action@v1.41
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 你的 GITHUB_TOKEN 用于将版本上传到 Github Release。
          goos: ${{ matrix.goos }}  # 运行程序的操作系统
          goarch: ${{ matrix.goarch }}  # 运行程序的架构
          goversion: ${{ env.GOVERSION }}  # Go 编译环境版本
          project_path: "./cmd/sing-box"  # 在哪里运行 go build 命令。
          binary_name: "${{ env.BINARY }}"  # 二进制名称
          build_flags: "-tags with_quic,with_grpc,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_gvisor"  # 传递给 go build 命令的其他参数
          ldflags: "-s -w --extldflags '-static -fpic' -X 'github.com/sagernet/sing-box/constant.Version=${{ ENV.VERSION }}'"  # ldflags参数
          md5sum: "false"
          release_tag: "v1.0.0"  # 上传的标签
          release_name: "test"  # 上传的名字
          compress_assets: "auto"  # 自定义打包
          asset_name: "${{ env.BINARY }}-${{ matrix.goos }}-${{ matrix.goarch }}"  # 自定义名称

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600
